from applehealth import AppleHealth
import numpy as np
import pandas as pd
ah = AppleHealth(readCache = True, writeCache = True)
# ah.resampleWorkouts({'duration' : np.mean})
# ah.workoutTrends('Soccer')
ah.resampleRecords({'BodyMass' : np.mean, 'DistanceWalkingRunning' : sum, 'StepCount' : sum, 'HeartRateVariabilitySDNN': np.mean, 'RestingHeartRate' : np.mean, 'AppleExerciseTime' : sum})
# ah.resampleWorkouts({'BodyMass' : np.mean, 'DistanceWalkingRunning' : sum, 'StepCount' : sum, 'HeartRateVariabilitySDNN': np.mean, 'RestingHeartRate' : np.mean, 'AppleExerciseTime' : sum})
# ah.extractWorkoutType('Soccer', 'soccer.csv')
# ah.sleepRecord()
# ah.sleepAnalysis()
# print(len(ah.pivot_record_df))
# print(ah.standardDeviationRecord())
# print(ah.standardDeviationWorkout())
# print(ah.workoutAvgEnergyBurnedPerMin('TraditionalStrengthTraining'))
# print(ah.workoutAvgDistancePerMin('Soccer'))
# print(ah.workoutAvgDistancePerMin('Swimming'))
# print(ah.workoutAvgDistancePerMin('Running'))
# print(len(ah.compressRecord('3T')))
# print(ah.avgRecordFreq())
# print(ah.record_df.isna().sum()/len(ah.record_df)*100)
# print(ah.pivot_record_df.isna().sum()/len(ah.pivot_record_df)*100)
# temp = ah.dropNullRecord(thresh = 0.8)
# print(temp.isna().sum()/len(temp)*100)
# ah.timeSeries('DistanceWalkingRunning')
# ah.heatMap()
# ah.pairPlot(['DistanceWalkingRunning', 'StepCount', 'HeartRateVariabilitySDNN', 'RestingHeartRate', 'AppleExerciseTime'])
# print(ah.narrowRange('2021-06-05 00:00:00-04:00', '2021-06-08 00:00:00-04:00'))
# print(ah.monthlyBar('DistanceWalkingRunning'))
key = ah.findWorkoutByTime('2020-6-6 14:00:0')
print(key)
print(ah.pivot_workout_df.loc[key].notnull())
print(ah.pivot_record_df.loc[key].notnull())
